# Generated by Django 3.0 on 2019-12-08 22:02

from django.db import migrations, models
import forms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('answer_type', models.CharField(choices=[(forms.models.QuestionType['MULTIPLE_CHOICE'], 'Escolha múltima'), (forms.models.QuestionType['SINGLE_CHOICE'], 'Escolha única'), (forms.models.QuestionType['OPEN_QUESTION'], 'Pergunta de texto aberta')], max_length=5)),
                ('priority', models.IntegerField(default=0)),
                ('question_templates', models.ManyToManyField(to='forms.QuestionTemplate')),
            ],
        ),
    ]
