# Generated by Django 3.0 on 2019-12-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=200)),
                ('answer_type', models.CharField(choices=[('MC', 'Escolha múltipla'), ('SC', 'Escolha única'), ('OQ', 'Pergunta de texto aberta')], max_length=5)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('answers', models.ManyToManyField(to='forms.Answer')),
            ],
        ),
    ]
