# Generated by Django 3.0 on 2019-12-08 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.QuestionTemplate')),
            ],
        ),
    ]
