# Generated by Django 3.0 on 2019-12-09 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20191208_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='offer',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='professors',
        ),
    ]
