# Generated by Django 3.0 on 2019-12-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20191209_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='professors',
            field=models.ManyToManyField(to='forms.Professor'),
        ),
    ]
