# Generated by Django 3.0 on 2019-12-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ManyToManyField(to='forms.Major'),
        ),
    ]
