# Generated by Django 3.0 on 2019-12-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='major',
            field=models.ManyToManyField(related_name='profile', to='forms.Major'),
        ),
    ]
