# Generated by Django 3.0 on 2019-12-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_auto_20191209_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='major',
            field=models.ManyToManyField(related_name='professors', to='forms.Major'),
        ),
    ]
