# Generated by Django 3.0 on 2019-12-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_professor_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forms.Major'),
            preserve_default=False,
        ),
    ]
