# Generated by Django 3.0 on 2019-12-09 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0012_offer_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='major', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
