# Generated by Django 3.0 on 2019-12-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_auto_20191209_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='major',
            old_name='major',
            new_name='user',
        ),
    ]
