# Generated by Django 3.0 on 2019-12-09 03:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0016_auto_20191209_0330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='major',
            name='major',
        ),
        migrations.AddField(
            model_name='major',
            name='user',
            field=models.ManyToManyField(related_name='major', to=settings.AUTH_USER_MODEL),
        ),
    ]
