# Generated by Django 3.0 on 2019-12-09 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0019_auto_20191209_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('CURSO', 'Pergunta geral do curso'), ('DISC', 'Pergunta para disciplinas'), ('PROF', 'Pergunta para professor')], max_length=5),
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('CURSO', 'Pergunta geral do curso'), ('DISC', 'Pergunta para disciplinas'), ('PROF', 'Pergunta para professor')], max_length=5)),
                ('form_application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.FormApplication')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.Offer')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.Professor')),
            ],
        ),
    ]
